import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '教学工具',
      collapsed: true,
      link: {type: 'doc', id: 'teaching-tools/index'},
      items: [{type: 'autogenerated', dirName: 'teaching-tools'}],
    },
    {
      type: 'category',
      label: '益智游戏',
      collapsed: true,
      link: {type: 'doc', id: 'games/index'},
      items: [{type: 'autogenerated', dirName: 'games'}],
    },
    {
      type: 'category',
      label: 'AI',
      collapsed: true,
      link: {type: 'doc', id: 'ai/index'},
      items: [{type: 'autogenerated', dirName: 'ai'}],
    },
  ],
};

export default sidebars;
